#ddev-generated
services:
  web:
    ports:
      - host_ip: 0.0.0.0
        mode: ingress
        protocol: tcp
        target: 80
        published: 80
      - host_ip: 0.0.0.0
        mode: ingress
        protocol: tcp
        target: 443
        published: 443
